## Reference: https://github.com/helm/chart-releaser-action
name: Publish Chart to Chartmuseum
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.1

      - name: Add uclalibrary helm repo
        run: |
          helm repo add uclalibrary https://chartmuseum.library.ucla.edu

      - name: Install ChartMuseum helm plugin
        run: |
          helm plugin install https://github.com/chartmuseum/helm-push

      - name: Build ArgoCD dependencies
        run: |
          helm dependency build charts/argo-cd

      - name: Publish ArgoCD helm chart to UCLA Library's Chartmuseum
        run: |
          helm cm-push charts/argo-cd uclalibrary -u ${CM_USERNAME} -p ${CM_PASSWORD}
        env:
          CM_USERNAME: "${{ secrets.CM_USERNAME }}"
          CM_PASSWORD: "${{ secrets.CM_PASSWORD }}"
